apiVersion: apps/v1
kind: Deployment
metadata:
  name: openaiops-deployment
  labels:
    app: openaiops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openaiops
  template:
    metadata:
      labels:
        app: openaiops
    spec:
      containers:
      - name: openaiops
        image: openaiops:latest
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: logs
          mountPath: /var/log/openaiops
      volumes:
      - name: logs
        emptyDir: {}